#if !canImport(ObjectiveC)
import XCTest

extension ApplicationAppleIDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicationAppleIDTests = [
        ("testCreation", testCreation),
        ("testCreationFromStringLiteral", testCreationFromStringLiteral),
        ("testSwiftUIEnvironment", testSwiftUIEnvironment),
        ("testURLAccessors", testURLAccessors),
    ]
}

extension ApplicationInfoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicationInfoTests = [
        ("testCreationFromEmptyBundle", testCreationFromEmptyBundle),
        ("testCreationFromLocalizedBundle", testCreationFromLocalizedBundle),
        ("testCreationFromUnlocalizedBundle", testCreationFromUnlocalizedBundle),
        ("testIdentifiableConformante", testIdentifiableConformante),
        ("testNamingAccessors", testNamingAccessors),
        ("testNamingEquatableConformance", testNamingEquatableConformance),
        ("testSwiftUIEnvironment", testSwiftUIEnvironment),
        ("testVersioningAccessors", testVersioningAccessors),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApplicationAppleIDTests.__allTests__ApplicationAppleIDTests),
        testCase(ApplicationInfoTests.__allTests__ApplicationInfoTests),
    ]
}
#endif
